POST http://localhost:3004/user
Content-Type: application/json

{
    "username" : "raju",
    "password": "raju@456",
    "gender":"male",
    "location" : "bengaluru"
}

###



### 

POST http://localhost:3004/login
Content-Type: application/json

{
    "username" : "raju",
    "password": "raju@456"
}
